### ISSUE TITLE
Error while dialing dial unix //run/starlight/starlight-daemon.sock: connect: permission denied

### ISSUE THREAD

**Issue by cstria0106** [mc256/starlight#26]
Hello. I'm trying Starlight for my research. I'm currently following this instruction: https://github.com/mc256/starlight/blob/master/docs/newbie.md

----

When I run command just like 'ctr-strlight convert ...' or 'ctr-starlight test', it prints permission error
```sh
$ ctr-starlight test test
notify starlight proxy server failed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix //run/starlight/starlight-daemon.sock: connect: permission denied"
```

But it works with sudo, like 'sudo ctr-starlight test test'
```sh
$ sudo ctr-starlight test test
ping test success: ok! - http://10.0.2.2:8090
latency: 1 ms
```

And it also works when I change starlight socket's permission explicitly
```sh
$ sudo chmod -R 777 /run/starlight
$ ctr-starlight test test         
ping test success: ok! - http://10.0.2.2:8090
latency: 30 ms
```

----

The environment: Ubuntu 22.04.1 LTS on VirtualBox

Thank you!

**Comment by mc256** [comment]
Thank you for trying out Starlight.

Sorry that the [newbie.md](https://github.com/mc256/starlight/blob/master/docs/newbie.md) is a bit outdated. It should only work for v1.3.0.

Most of the commands are required to run in `sudo`. Similarly, the `ctr` command usually requires `sudo` (There are "rootless" containers, but we are not there yet). `ctr-starlight test` is a newly implemented feature, so it is not available in v1.3.0. Therefore, I guess that you are using a newer version of Starlight. I will update the document.
The error message does not provide helpful information, and I will update that.

I will double-check and update this Issue shortly.

**Comment by cstria0106** [comment]
Thank you for answer! I will try with v1.3.0.

**Comment by mc256** [comment]
Hi @cstria0106, If you are not in a hurry, could you hold on for a day? I will update the document for the newer version this weekend. It would be awesome if you had the opportunity to try the latest version with all the newly implemented features.

Thanks a lot!

**Comment by cstria0106** [comment]
Sure! I'm reading and trying various papers to find my research topic, and Starlight is the first. I would appreciate it if you could update the document because I am thinking of taking a long time to try it.

It would be really helpful if I could try the latest version. Thank you!

**Comment by mc256** [comment]
Hi @cstria0106 ,

I have tested this on AWS using two `t2.micro` machines using `Ubuntu 22.04` (kernel `5.15.0-1026-aws`). And I hope that it works on your virtual box. The kernel version needs to be greater than `5.15.0-52` (you could check it using `uname -r`)

---

There are two issues that I came across while updating the documentation, so I have to make some changes to the code a bit. I leave it here to document it:
- The starlight proxy does not correctly identify the insecure registry
  ```
  proxy_1     | time="Jan  8 16:11:17.584495750" level=info msg="request received" action=notify ip="34.225.141.**:51584"
  proxy_1     | time="Jan  8 16:11:17.586349613" level=error msg="failed to cache ToC" error="failed to cache ToC: Get \"https://100.25.49.***:5000/v2/\": http: server gave HTTP response to HTTPS client"
  ```
  I tried using the IP address and domain name, but they all resolved to HTTPS. Because it works on Kubernetes, I try to follow the DNS naming in Kubernetes and use `cloud.starlight.cluster.local`, and it works. This is a hack. But it is too much work to get `--insecure` work on `ctr-starlight pull`, so I will leave that to later updates.

  That means we will have to change the `/etc/hosts` file to make `cloud.starlight.cluster.local` resolving to the "cloud" server.
- The container config has not been handled properly. (I am still not sure where this bug is)
  So I specify the container `COMMAND` when we launch the container. Ideally, this should be set by the container config.
 

---


BTW, I am not sure what project you want to do (you don't have to tell me). We mainly use this tool with Kubernetes (i.e. K3s) for our IoT devices. If you're going to speed up Python or Node.js app deployment on the Edge IoT device (e.g. Raspberry Pi), I recommend you use k3s (a lightweight Kubernetes) and follow the guide in [docs/helm.md](https://github.com/mc256/starlight/blob/master/docs/helm.md). Although this [docs/helm.md](https://github.com/mc256/starlight/blob/master/docs/helm.md) does not include how to set up a Kubernetes cluster, It should have fewer steps in total (including installing k3s in two VMs). 

There are some docs about how to set up k3s and helm:
- https://docs.k3s.io/quick-start
- https://helm.sh/docs/intro/install/
- I will also write an article about setting up a k3s cluster...


 [docs/newbie.md](https://github.com/mc256/starlight/blob/master/docs/newbie.suitableis good for having a minimum viable product so that we can benchmark and debug Starlight or benchmark the file system. But without the help from Kubernetes, launching a container and scaling it would be a problem.


Please let me know whether it works or not.

**Comment by cstria0106** [comment]
It runs properly as described in the tutorial. Thank you

**Comment by mc256** [comment]
No problem! I am happy to hear that! 
If you have come across other problems, please create another issue.
